FROM node:16-alpine

ARG DATABASE_URL
ARG PORT

WORKDIR /usr/app

COPY . .

RUN yarn install

#RUN npx prisma migrate deploy

RUN npx prisma generate

RUN yarn next:build

RUN yarn build


#EXPOSE ${PORT}

ENTRYPOINT ["yarn", "prod:start"]
